<?php

namespace AppBundle\Repository;

/**
 * GezinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GezinRepository extends \Doctrine\ORM\EntityRepository
{
}
