<?php

namespace AppBundle\Repository;

/**
 * uitgaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uitgaveRepository extends \Doctrine\ORM\EntityRepository
{
}
