<?php

namespace AppBundle\Repository;

/**
 * WinkelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinkelRepository extends \Doctrine\ORM\EntityRepository
{
}
