# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
       AppBundle\Entity\Gebruiker:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        app_user_provider:
            entity:
                class: AppBundle\Entity\Gebruiker
                property: gebruikersnaam


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: login[_username]
                password_parameter: login[_password]
                target_path_parameter: login[_target_path]
            logout:
              path: /logout

    access_control:
        - { path: ^/overview, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }